- name: "[FILE-7524] Harden filesystem"
  file:
    path: '{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - {'path':'/etc/at.deny', 'mode':'0640'}
    - {'path':'/etc/cron.d', 'mode':'0755'}
    - {'path':'/etc/cron.daily', 'mode':'0755'}
    - {'path':'/etc/cron.hourly', 'mode':'0755'}
    - {'path':'/etc/cron.monthly', 'mode':'0755'}
    - {'path':'/etc/cron.weekly', 'mode':'0755'}
    - {'path':'/etc/crontab', 'mode':'0644'}
    - {'path':'/etc/ssh/sshd_config', 'mode':'0644'}
