- name: "[FIRE-4512] Purge UFW with extreme prejudice"
  apt:
    name: ufw
    state: absent

- name: "[FIRE-4512] Install iptables-persistent"
  apt:
    name: iptables-persistent
    state: present

- name: "[FIRE-4512] Install iptables rules"
  copy:
    src: iptables.rules.v4
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0640
  notify:
    - Reload iptables
