- name: "[KRNL-6000] Harden sysctl"
  lineinfile:
    path: '/etc/sysctl.d/99-KRNL-6000.conf'
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} = {{ item.value }}'
    create: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - {'key':'dev.tty.ldisc_autoload', 'value':'0'}
    - {'key':'fs.protected_fifos', 'value':'2'}
    - {'key':'fs.suid_dumpable', 'value':'0'}
    - {'key':'kernel.core_uses_pid', 'value':'1'}
    - {'key':'kernel.dmesg_restrict', 'value':'1'}
    - {'key':'kernel.kptr_restrict', 'value':'1'}
      #- {'key':'kernel.modules_disabled', 'value':'1'}
    - {'key':'kernel.sysrq', 'value':'0'}
    - {'key':'kernel.unprivileged_bpf_disabled', 'value':'1'}
    - {'key':'net.core.bpf_jit_harden', 'value':'2'}
    - {'key':'net.ipv4.conf.all.accept_redirects', 'value':'0'}
    - {'key':'net.ipv4.conf.all.log_martians', 'value':'1'}
    - {'key':'net.ipv4.conf.all.rp_filter', 'value':'1'}
    - {'key':'net.ipv4.conf.all.send_redirects', 'value':'0'}
    - {'key':'net.ipv4.conf.default.accept_redirects', 'value':'0'}
    - {'key':'net.ipv4.conf.default.accept_source_route', 'value':'0'}
    - {'key':'net.ipv4.conf.default.log_martians', 'value':'1'}
    - {'key':'net.ipv6.conf.all.accept_redirects', 'value':'0'}
    - {'key':'net.ipv6.conf.default.accept_redirects', 'value':'0'}
  notify:
    - Reload sysctl
